salesforceBaseUrl = ""
port = 3306
host = ""
user = ""
password = ""
database = ""

[integration_samples.mysql_record_to_sfdc_new_product.salesforceOAuthConfig]
clientId = ""
clientSecret = ""
refreshToken = ""
refreshUrl = ""
